interface Deferred {
  uri: string;
}

interface SharePointUser {
  Id: number;
  Title?: string;
  [key: string]: any;
}

interface SharePointMetadata {
  id: string;
  uri: string;
  etag: string;
  type: "SP.Data.ChangePreInvoiceRowHistoryListItem";
}

export interface IChangePreInvoiceRowHistoryListItem {
  ID: number;
  Title: string;
  STW: string;
  printTitle: string;
  printType: string;
  productTittle: string;
  colorFinalCode: string;
  colorTitle: string;
  packingTitle: string;
  preInvoiceProductTitle: string;
  finalGenerationCode: string;
  finalProductCode: string;
  packingCode: string;
  orderNumber: string;
  productCode: string;
  amount: string;
  productionAmount: string;
  price: string;
  totalPrice: string;
  productCatgory: string;
  status: string;
  coverColor: string;
  colorString: string;
  customerName: string;
  customerCode: string;
  preInvoiceCreateDate: string;
  packingType: string;
  packingMaterial: string;
  packingSize: string;
  packingM: string;
  Created: string | Date;
  Modified: string | Date;
  Author: SharePointUser;
  Editor: SharePointUser;
  ContentTypeId?: string;
  OData__UIVersionString?: string;
  Attachments?: boolean;
  GUID?: string;
  _ModerationStatus?: number;
  _ModerationComments?: string;
  AttachmentFiles?: Deferred;
  ContentType?: Deferred;
  File?: Deferred;
  Folder?: Deferred;
  FileSystemObjectType?: number;
  __metadata: SharePointMetadata;
  [key: string]: any;
}

export interface IBastebandiListItem {
  Id: number;
  Title?: string;
  printTitle?: string;
  printType?: string;
  productTittle?: string;
  colorFinalCode?: string;
  colorTitle?: string;
  packingTitle?: string;
  preInvoiceProductTitle?: string;
  finalGenerationCode?: string;
  finalProductCode?: string;
  packingCode?: string;
  orderNumber?: string;
  orderNumberRow?: string;
  productCode?: string;
  amount?: string;
  productionAmount?: string;
  price?: string;
  totalPrice?: string;
  productCatgory?: string;
  Created: string | Date;
  Modified: string | Date;
  AuthorId?: number;
  EditorId?: number;
  ContentTypeId?: string;
  OData__UIVersionString?: string;
  Attachments?: boolean;
  GUID?: string;
  _ModerationStatus?: number;
  _ModerationComments?: string;
  FileSystemObjectType?: number;
  add?: boolean;
  bastebandie?: string;
  chap?: string;
  codegoods?: string | null;
  codemahsol?: string;
  codemoshtari?: string;
  jensebaste?: string;
  meghdarbarnamerizitakonon?: string | null;
  metraj?: string;
  metrajtahvili?: string | null;
  metrebaste?: string;
  moshtari?: string | null;
  name?: string;
  namegoods?: string | null;
  rang?: string;
  rangrokesh?: string | null;
  shomarefactor?: string;
  shomarefactor0?: string;
  shomaretarh?: string;
  sizebaste?: string;
  sodorcart?: boolean;
  tarikhsefaresh?: string;
  tozihat?: string | null;
  typebaste?: string;
}

export interface IBastebandiShodeListItem {
  Id: number;
  Title?: string;
  printTitle?: string;
  printType?: string;
  productTittle?: string;
  colorFinalCode?: string;
  colorTitle?: string;
  packingTitle?: string;
  preInvoiceProductTitle?: string;
  finalGenerationCode?: string;
  finalProductCode?: string;
  packingCode?: string;
  orderNumber?: string;
  orderNumberRow?: string;
  productCode?: string;
  amount?: string;
  productionAmount?: string;
  price?: string;
  totalPrice?: string;
  productCatgory?: string;
  Created: string | Date;
  Modified: string | Date;
  AuthorId?: number;
  EditorId?: number;
  ContentTypeId?: string;
  OData__UIVersionString?: string;
  Attachments?: boolean;
  GUID?: string;
  _ModerationStatus?: number;
  _ModerationComments?: string;
  FileSystemObjectType?: number;
  add?: boolean;
  bastebandie?: string;
  chap?: string;
  codegoods?: string | null;
  codemahsol?: string;
  codemoshtari?: string;
  jensebaste?: string;
  meghdarbarnamerizitakonon?: string | null;
  metraj?: string | null;
  metrajtahvili?: string | null;
  metrebaste?: string;
  moshtari?: string | null;
  name?: string;
  namegoods?: string | null;
  rang?: string;
  rangrokesh?: string | null;
  shomarefactor?: string;
  shomarefactor0?: string;
  shomaretarh?: string;
  sizebaste?: string;
  sodorcart?: boolean;
  tarikhsefaresh?: string;
  tozihat?: string | null;
  typebaste?: string;
  Meghdartahvilibastebandi?: string | null;
  Meghdartahvilibastebandisum?: string | null;
  Number_barname?: string | null;
  OData__x062a__x0633__x062a_?: string | null;
  OData__x062e__x0627__x0644__x06?: number;
  OData__x0641__x0631__x0622__x06?: number;
  ROWS?: number;
  Size?: string;
  Tahvilanbar?: boolean;
  code_15r?: string;
  codemahsolemoshtari?: string | null;
  coler_final_code?: string;
  color_difaltcode?: string;
  colertitle?: string;
  controlkeyfi?: string | null;
  excle?: boolean;
  ezafetolid?: string | null;
  ezafetolidt?: string | null;
  ezafetolidyes?: boolean;
  ghotr?: string;
  goods_title?: string;
  goodscode?: string;
  meghdartahvili?: string | null;
  metrajdarkhasti?: string;
  metrajtolid?: string | null;
  namintabegh?: string | null;
  newedit?: boolean;
  notview?: boolean;
  packing_code?: string;
  packing_name?: string;
  payantolid?: boolean;
  pelast?: boolean;
  printlabel?: boolean;
  radyabi?: string | null;
  sharhmahsolemoshtari?: string;
  tarikhtahvil?: string | null;
  tarikhtolid?: string | null;
  timebarname?: string;
  vaznekol?: string | null;
  vaznkhales?: string | null;
  yebar?: string | null;
}

export interface IOrderProductsListItem {
  Id: number;
  Title?: string;
  Amount?: string | null;
  Approve?: string | null;
  AssignedToId?: number | null;
  Attachments?: boolean;
  AuthorId?: number;
  Body?: string | null;
  Checkmark?: string;
  Color?: string;
  ContentTypeId?: string;
  CopperWeight?: string | null;
  CoverColor?: string | null;
  Created: string | Date;
  Customer?: string;
  CustomerCode?: string;
  DashedColor?: string | null;
  Date?: string | null;
  Date0?: string;
  DueDate?: string | null;
  EditorId?: number;
  FileSystemObjectType?: number;
  GUID?: string;
  Modified: string | Date;
  OData__UIVersionString?: string;
  OData__x062b__x0628__x062a__x0020__x06?: string | null;
  OData__x067e__x0631__x06a9__x0631__x06?: string | null;
  OData__x067e__x0631__x06a9__x0631__x060?: string | null;
  OData__x0628__x0633__x062a__x0647__x06?: string | null;
  OldCode?: string | null;
  OrderNumber?: string;
  OrderRemained?: string | null;
  OrderRowNo?: string;
  PackLength?: string;
  PackMaterial?: string;
  PackSize?: string;
  PackType?: string;
  Packing?: string;
  Percent?: string | null;
  PercentComplete?: number;
  Print?: string;
  PrintStatus?: string | null;
  Priority?: string;
  ProductionCode?: string;
  ProductionStatus?: string;
  Ran?: string | null;
  RanMeter?: number;
  Remain?: string | null;
  StartDate?: string | null;
  Status?: string;
  Status0?: string | null;
  StopWF?: string | null;
  Tolerance?: string | null;
  Updated_Material?: string;
  Updated_Package?: string;
  Updated_Production?: string;
  WFOrderA?: string | null;
  WFOrderP?: string | null;
  WFOrderP0?: number;
  WFOrderP1?: string | null;
  WFOrderP2?: string | null;
  WFOrderP3?: string | null;
  WFOrderP4?: string | null;
  add?: boolean;
  code_goods?: string | null;
  marhaletolid_akharin?: string | null;
  name_goods?: string | null;
  nimesakhte?: boolean;
  orderpro?: string | null;
  productMeter?: number;
  remaintemp?: string | null;
  shomare_akharin?: string;
  test?: string | null;
  test1?: string | null;
}

export interface IPishraftMarahelTolidItem {
  Id: number;
  Title?: string;
  AuthorId?: number;
  EditorId?: number;
  Created: string | Date;
  Modified: string | Date;
  ContentTypeId?: string;
  OData__UIVersionString?: string;
  Attachments?: boolean;
  GUID?: string;
  OData__x06cc__x0628__x0627__x0631_?: string | null;
  OData__x0622__x062e__x0631__x06cc__x06?: string | null;
  TEST?: string | null;
  Value?: string | null;
  akharinmarhale?: boolean;
  arzenavar?: string | null;
  arzenavaralminiom?: string | null;
  arzenavarmailar?: string | null;
  barnamerizishode?: boolean;
  bastebandi?: string;
  chidemanreshtelayeha?: string | null;
  chidemanreshtelayeha2?: string | null;
  chidemanreshtelayeha3?: string | null;
  chidemanreshtelayeham?: string | null;
  codeekhtesari?: string;
  codemahsol?: string;
  date?: string | null;
  datesefaresh?: string;
  diff?: string;
  ghotremaftolfoladi?: string | null;
  ghotrereshte?: string | null;
  halatekeshesh?: string | null;
  idakharinbarnamerizi?: string | null;
  idlevel?: string;
  idproductionPlanproductgroup1?: string;
  jahatetab?: string | null;
  jahattab2?: string | null;
  jahattab3?: string | null;
  jahattabm?: string | null;
  marhaletolid?: string;
  matnechap?: string;
  maxghotreayeghshode?: string;
  maxghotrershte?: string | null;
  maxtoltab?: string | null;
  maxtoltabmarkaz?: string | null;
  meghdarbarnamerizitakonon?: number;
  mindama?: string | null;
  minghotreayeghshode?: string;
  minghotrershte?: string | null;
  minrotobat?: string | null;
  mintoltab?: string | null;
  mintoltabmarkaz?: string | null;
  namedastgah?: string;
  namemoshtari?: string;
  nameoperator?: string | null;
  poshesh?: string | null;
  rangbandi?: string;
  rangrokesh?: string | null;
  sazeghaleb?: string;
  shomaremarhale?: string;
  shomaresefaresh?: string;
  shomaretarh?: string;
  shomareverjen?: string;
  size?: string;
  sizenazel?: string;
  sizesimert?: string | null;
  tarikhbarnamerizighabli?: string | null;
  tedadarmor?: string | null;
  tedadmaftolfoladi?: string | null;
  tedadreshte?: string | null;
  tedadreshtebarayemarahel?: string | null;
  tedadvaghotreshte?: string | null;
  tolidbarnamei?: number;
  tolidvaghei?: number;
  toltabmax2?: string | null;
  toltabmax3?: string | null;
  toltabmin2?: string | null;
  toltabmin3?: string | null;
  tozihat?: string | null;
  typelevel?: string | null;
  typename?: string;
  typesefaresh?: string;
  vijegikhas?: string | null;
  zamanotaghbokhar?: string | null;
  zaribtab?: string | null;
  zekhamatenavaralminiom?: string | null;
  zekhamatmotevaset?: string;
  zekhamatnavarmailar?: string | null;
  zekhamatnoghtei?: string;
}

export interface IDetailCustomerFactorListItem {
  Id: number;
  Title?: string;
  Actionator?: string | null;
  Amount?: string;
  Attachments?: boolean;
  AuthorId?: number;
  Category?: string;
  Color?: string | null;
  Color2?: string | null;
  ContentTypeId?: string;
  Created: string | Date;
  Customer?: string;
  CustomerCode?: string | null;
  Date?: string;
  DayDelivary?: string | null;
  DelivaryDate?: string | null;
  Description?: string | null;
  EditorId?: number;
  FileSystemObjectType?: number;
  GUID?: string;
  Grade?: string;
  Issue?: string | null;
  MeasuiementUnit?: string;
  Meter?: string | null;
  Modified: string | Date;
  NumberProgram?: string | null;
  OData__UIVersionString?: string;
  OData__x0070_1?: string;
  OData__x0070_2?: string | null;
  OData__x0070_3?: string | null;
  OData__x0070_4?: string;
  OldCode?: string | null;
  OrderNumber?: string;
  OriginalColor?: string | null;
  Packing?: string;
  Price?: string;
  Print?: string | null;
  Product?: string;
  ProductDisplayName?: string;
  ProductSize?: string;
  Production?: string | null;
  ProductionCode?: string | null;
  ProgramNumber?: string | null;
  Ran?: string;
  RanMeter?: string | null;
  Revised_Request?: string;
  STW?: string;
  Standard?: string | null;
  StartDate?: string | null;
  Status?: string | null;
  StatusPrefactor?: string | null;
  StringColor?: string;
  StringColor_code?: string;
  Structure?: string;
  TextPrint?: string;
  Tolerance?: string | null;
  UnitGoods?: string | null;
  Value?: string;
  Voltage?: string;
  WFCreate?: string | null;
  add?: boolean;
  code_15r?: string | null;
  codegoods?: string | null;
  codemahsolemoshtari?: string | null;
  coler_final_code?: string | null;
  colertitle?: string | null;
  color_difaltcode?: string | null;
  cu?: string;
  darsad_takhfif?: string;
  date_c?: string | null;
  date_k?: string | null;
  goods_title?: string | null;
  goodscode?: string | null;
  idparent?: string;
  marhaletolid_akharin?: string | null;
  meghdarjahattolid?: string;
  namegoods?: string | null;
  nimesakhte?: boolean;
  notview?: boolean;
  packing_code?: string | null;
  packing_name?: string | null;
  parent_code?: string;
  parent_ditaile_code?: string;
  pidId?: number;
  pidroutinId?: string | null;
  rang_rokesh_code?: string | null;
  rang_rows?: string;
  rows?: number;
  shomare_akharin?: string;
  titlefrest?: string | null;
  tu?: string;
}

export interface IProductionPlanListItem {
  AttachmentFiles?: string | null;
  Attachments: boolean;
  AuthorId: number;
  ContentType?: string | null;
  ContentTypeId: string;
  Created: string;
  EditorId: number;
  FieldValuesAsHtml?: string | null;
  FieldValuesAsText?: string | null;
  FieldValuesForEdit?: string | null;
  File?: string | null;
  FileSystemObjectType: number;
  FirstUniqueAncestorSecurableObject?: string | null;
  Folder?: string | null;
  GUID: string;
  GetDlpPolicyTip?: string | null;
  ID: number;
  Id: number;
  Modified: string;
  OData__UIVersionString: string;
  OData__x062a__x06a9__x0631__x0627__x06?: number | null;
  OData__x062a__x0633__x062a_?: string | null;
  OData__x062d__x0627__x0644__x062a__x06?: string | null;
  OData__x067e__x0631__x06a9__x0631__x061?: number | null;
  OData__x067e__x0631__x06a9__x0631__x062?: string | null;
  OData__x0645__x0642__x062f__x0627__x06?: string | null;
  ParentList?: string | null;
  RoleAssignments?: string | null;
  Title: string;
  akharin_x0020_gerefteshodeazmaza?: string | null;
  akharinmarhale: boolean;
  akharinmazadtolid: number;
  arzenavar?: string | null;
  arzenavaralminiom?: string | null;
  arzenavarmailar?: string | null;
  barnameriziaztarike: string;
  barnamerizitatarikhe: string;
  bastebandi?: string | null;
  carttolid: boolean;
  chidemanreshtelayeha?: string | null;
  chidemanreshtelayeha2?: string | null;
  chidemanreshtelayeha3?: string | null;
  chidemanreshtelayeham?: string | null;
  codemahsol: string;
  diff: string;
  estefadedar?: string | null;
  estefademeghdar: number;
  ghotremaftolfoladi?: string | null;
  idprint?: string | null;
  idproductionPlanproductgroup1: string;
  jahattab?: string | null;
  jahattab2?: string | null;
  jahattab3?: string | null;
  jahattabm?: string | null;
  mahsoletolidi: string;
  matnechap?: string | null;
  mavadbari: boolean;
  maxghotreayeghshode?: string | null;
  maxghotrershte: string;
  maxtoltabmarkaz?: string | null;
  meghdareestefadeshodeazdigharmaz?: string | null;
  meghdarkolesefaresh: string;
  meghdartoliddaremroz: string;
  mindama?: string | null;
  minghotreayeghshode?: string | null;
  minghotrershte: string;
  minrotobat?: string | null;
  mintoltabmarkaz?: string | null;
  namedastghah: string;
  namemarhale: string;
  namemoshtari: string;
  nameoperator?: string | null;
  poshesh?: string | null;
  productionplanid?: string | null;
  rangbandi?: string | null;
  rangrokesh?: string | null;
  shomarebarnamemavad?: string | null;
  shomarebarnamerizi: string;
  shomarecart: string;
  shomaremarhale: string;
  shomareradiffactor: string;
  shomareverjen: string;
  size: string;
  sizeghaleb: string;
  sizenazel?: string | null;
  sizesimert?: string | null;
  tarhetolid: string;
  tarikhbarnamerizi: string;
  tedadarmor?: string | null;
  tedadmaftolfoladi?: string | null;
  tedadreshte: string;
  tolidvaghei?: string | null;
  toltabmax?: string | null;
  toltabmax2?: string | null;
  toltabmax3?: string | null;
  toltabmin?: string | null;
  toltabmin2?: string | null;
  toltabmin3?: string | null;
  tozihat?: string | null;
  tozihattolid?: string | null;
  typeertorhadi?: string | null;
  typekeshesh: string;
  typename: string;
  typesefaresh: string;
  vijegihayekhas?: string | null;
  yyyyyy?: string | null;
  zamanotaghbokhar?: string | null;
  zaribtab?: string | null;
  zekhamatenavaralminiom?: string | null;
  zekhamatmotevaset?: string | null;
  zekhamatnavarmailar?: string | null;
  zekhamatnoghtei?: string | null;
}
